"""
Forge Core — dbt Runner Module

Handles dbt command execution via subprocess or dbtRunner.
"""

import os
import sys
import io
import shlex
import subprocess
from datetime import datetime
from typing import Optional, List, Dict
import logging

# Import dbt runner for in-process execution
try:
    from dbt.cli.main import dbtRunner, dbtRunnerResult
except ImportError:
    dbtRunner = None

logger = logging.getLogger(__name__)


def update_dbtignore(
    models_to_exclude: List[str], dbt_dir: str = None
):
    """
    Updates .dbtignore to exclude specified models.

    Args:
        models_to_exclude: List of model file names or patterns to exclude
        dbt_dir: Path to dbt project directory
    """
    if dbt_dir is None:
        dbt_dir = "./forge_project"

    dbtignore_path = os.path.join(dbt_dir, ".dbtignore")

    existing_models = set()
    if os.path.exists(dbtignore_path):
        with open(dbtignore_path, "r") as f:
            existing_models = {
                line.strip() for line in f if line.strip() and not line.startswith("#")
            }

    all_models = existing_models.union(set(models_to_exclude))

    with open(dbtignore_path, "w") as f:
        f.write("# Auto-generated by Forge Core\n")
        for model in sorted(all_models):
            f.write(f"{model}\n")

    logger.info(f"Updated .dbtignore with {len(models_to_exclude)} models")


def run_dbt_command(
    command: str,
    project_dir: str = None,
    extra_args: Optional[List[str]] = None,
    timeout: Optional[int] = None,
    env: Optional[Dict[str, str]] = None,
) -> subprocess.CompletedProcess:
    """
    Executes a dbt command with flexible configuration.

    Args:
        command: The dbt command to execute (e.g., "dbt build")
        project_dir: Working directory for dbt project
        extra_args: Additional command-line arguments
        timeout: Command timeout in seconds (optional)
        env: Additional environment variables to merge with os.environ

    Returns:
        subprocess.CompletedProcess (or compatible) result
    """
    if project_dir is None:
        project_dir = "./forge_project"

    # Build command as list for safety
    if isinstance(command, str):
        cmd_parts = shlex.split(command)
        if not cmd_parts or cmd_parts[0] != "dbt":
            cmd_parts = ["dbt"] + cmd_parts
    else:
        cmd_parts = list(command)

    if extra_args:
        cmd_parts.extend(extra_args)

    # Merge environment variables
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)

    # Set up logging
    log_file = os.path.join(project_dir, "logs", "user_audit.log")
    os.makedirs(os.path.dirname(log_file), exist_ok=True)

    timestamp = datetime.now().isoformat()
    command_str = " ".join(cmd_parts)

    with open(log_file, "a") as f:
        f.write(f"\n{'='*80}\n")
        f.write(f"TIMESTAMP: {timestamp}\n")
        f.write(f"COMMAND: {command_str}\n")
        f.write(f"CWD: {project_dir}\n")
        f.write(f"{'='*80}\n")

    logger.info(f"Executing: {command_str} (cwd: {project_dir})")

    # Try to use dbtRunner for in-process execution if available
    use_dbtrunner = dbtRunner is not None and cmd_parts[0] == "dbt"

    if use_dbtrunner:
        dbt_args = cmd_parts[1:]

        capture_stdout = io.StringIO()
        capture_stderr = io.StringIO()

        original_stdout = sys.stdout
        original_stderr = sys.stderr
        original_cwd = os.getcwd()

        try:
            abs_project_dir = os.path.abspath(project_dir)
            logger.info(f"Changing directory to: {abs_project_dir}")
            os.chdir(abs_project_dir)

            sys.stdout = capture_stdout
            sys.stderr = capture_stderr

            old_env = {}
            if env:
                for key, value in env.items():
                    old_env[key] = os.environ.get(key)
                    os.environ[key] = value

            runner = dbtRunner()
            result = runner.invoke(dbt_args)

            if env:
                for key in env.keys():
                    if old_env[key] is None:
                        os.environ.pop(key, None)
                    else:
                        os.environ[key] = old_env[key]

            sys.stdout = original_stdout
            sys.stderr = original_stderr
            os.chdir(original_cwd)

            stdout_content = capture_stdout.getvalue()
            stderr_content = capture_stderr.getvalue()

            class DbtResult:
                def __init__(self, success, stdout, stderr):
                    self.returncode = 0 if success else 1
                    self.stdout = stdout
                    self.stderr = stderr

            result_obj = DbtResult(result.success, stdout_content, stderr_content)

            with open(log_file, "a") as f:
                if stdout_content:
                    f.write(f"STDOUT:\n{stdout_content}\n")
                if stderr_content:
                    f.write(f"STDERR:\n{stderr_content}\n")

            return result_obj

        except Exception as e:
            sys.stdout = original_stdout
            sys.stderr = original_stderr
            os.chdir(original_cwd)
            logger.error(f"dbtRunner failed: {e}", exc_info=True)
            # Fall through to subprocess

    # Fallback to subprocess
    abs_project_dir = os.path.abspath(project_dir)
    logger.info(f"Running subprocess with cwd: {abs_project_dir}")

    try:
        result = subprocess.run(
            cmd_parts,
            cwd=abs_project_dir,
            env=merged_env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as e:
        logger.error(f"Command timed out after {timeout}s")
        raise

    with open(log_file, "a") as f:
        if result.stdout:
            f.write(f"STDOUT:\n{result.stdout}\n")
        if result.stderr:
            f.write(f"STDERR:\n{result.stderr}\n")

    return result
